---
# This file configures https://pre-commit.com/
# to use specific hooks and options.

fail_fast: false

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.7.1
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            assets/docker_hub_workflow.png
          )$
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      - id: shellcheck
      - id: shfmt

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.11.1
    hooks:
      - id: yamllint
        args: ['--format', 'parsable', '--strict']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
