---
# https://circleci.com/docs/docker
version: 2

workflows:
  version: 2

  commits:
    jobs:
      - build

jobs:
  build:
    docker:
      # https://github.com/jumanjihouse/cci/pulls?q=is%3Apr+is%3Aclosed
      - image: jumanjiman/cci:20180707T2325-git-e2f6fbf

    working_directory: ~/wtf/

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Prepare the local dev environment
          command: |
            ci/bootstrap

      - run:
          name: Build the image
          command: |
            ci/build

      - run:
          name: Test the image
          command: |
            ci/test

      - deploy:
          name: Deploy from master branch
          # yamllint disable rule:line-length
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              ci/publish
            fi
