# https://circleci.com/docs/docker
version: 2
jobs:
  build:
    docker:
      - image: jumanjiman/cci:20170812T1310-git-655b42a

    working_directory: ~/wtf/

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Build the image
          command: |
            ci/build

      - run:
          name: Test the image
          command: |
            ci/test

      - deploy:
          name: Deploy from master branch
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              ci/publish
            fi
