---
# https://circleci.com/docs/docker
version: 2.1

workflows:
  commits:
    jobs:
      - build

  # NOTE: autobuild was previously triggered via an API call
  #       from my VPS in Digital Ocean.
  #
  #       Use `git checkout 1a5095c' to view the old scripts.
  #
  #       CircleCI schedule does NOT support cron step values (/).
  awscli_stable:
    jobs:
      - build:
          awscli_version: "latest"
          autobuild: "true"
    triggers:
      - schedule:
          cron: '3 * * * *'
          #      ^ ^ ^ ^ ^
          #      | | | | |
          #      | | | | +-- Day of the week (0-6 with 0=Sunday)
          #      | | | +---- Month of the year (1-12)
          #      | | +------ Day of the month (1-31)
          #      | +-------- Hour (0-23)
          #      +---------- Minute (0-59)
          filters:
            branches:
              only:
                - master

  awscli_v2:
    jobs:
      - build:
          awscli_version: "2.0.0dev0"
    triggers:
      - schedule:
          cron: '0 1 * * *'
          #      ^ ^ ^ ^ ^
          #      | | | | |
          #      | | | | +-- Day of the week (0-6 with 0=Sunday)
          #      | | | +---- Month of the year (1-12)
          #      | | +------ Day of the month (1-31)
          #      | +-------- Hour (0-23)
          #      +---------- Minute (0-59)
          filters:
            branches:
              only:
                - master

jobs:
  build:
    parameters:
      autobuild:
        description: "Should we check to see if an image is already up-to-date?"
        type: string
        default: "false"

      awscli_version:
        description: "Which version of awscli should we install?"
        type: string
        default: "latest"

    docker:
      # https://github.com/jumanjihouse/cci/pulls?q=is%3Apr+is%3Aclosed
      - image: jumanjiman/cci:20180923T1521-git-a75cb83

    working_directory: ~/wtf/

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Prepare the local dev environment
          command: |
            ci/bootstrap

      - run:
          name: Build the image
          command: |
            VERSION='<< parameters.awscli_version >>' AUTOBUILD='<< parameters.autobuild >>' ci/build

      - run:
          name: Test the image
          command: |
            ci/test

      - deploy:
          name: Deploy from master branch
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              ci/publish
            fi
