#!/bin/bash
set -e
set -u

# WARNING
#
# ${CIRCLE_TOKEN} must be defined in the systemd service unit.
#

_project="jumanjihouse/docker-aws"
_branch="master"

trigger_build_url=https://circleci.com/api/v1.1/project/github/${_project}/tree/${_branch}?circle-token=${CIRCLE_TOKEN}

post_data=$(cat <<EOF
{
  "build_parameters": {
    "AUTOBUILD": "true"
  }
}
EOF
)

curl \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--data "${post_data}" \
--request POST ${trigger_build_url}
