#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Prepare the local dev environment.
# Invoke from the root of the git repo as "ci/bootstrap".
################################################################################
. ci/helpers.sh

main() {
  setup_python_path
  show_environment
  install_precommit
}

setup_python_path() {
  PYTHON_PATH="$(python -c "import site; print(site.USER_BASE)")"
  readonly PYTHON_PATH

  if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &>/dev/null; then
    export PATH="${PATH}:${PYTHON_PATH}/bin"
  fi
}

show_environment() {
  info 'Environment variables:'
  indent "$(env)"
}

install_precommit() {
  if command -v pre-commit &>/dev/null; then
    info 'pre-commit is already installed'
  else
    run pip install --user -Iv --compile --no-cache-dir --disable-pip-version-check pre-commit
  fi
}

main
