#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Publish the aws images to Docker Hub.
################################################################################
. ci/helpers.sh
. ci/vars

main() {
  if [[ ${UP2DATE} == true ]]; then
    info 'Image is up-to-date on docker hub; nothing to do.'
  else
    publish
  fi

  # Ensure Microbadger has latest metadata.
  poke_microbadger
}

publish() {
  # shellcheck disable=SC2154
  docker login -u "${user}" -p "${pass}"
  run docker tag jumanjiman/aws jumanjiman/aws:"${TAG}"
  run docker push jumanjiman/aws:"${TAG}"
  if [[ ${VERSION} =~ dev ]]; then
    info 'Do not publish the unstable dev version as "latest".'
  else
    run docker push jumanjiman/aws:latest
  fi
  docker logout
}

poke_microbadger() {
  echo -n '[INFO] microbadger '
  curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/aws/Lan3ZPTzecbxGrzvkdxR-dTxIB8='
  echo
}

main
