#!/bin/bash
set -e

. ci/vars
[[ ${UP2DATE} = true ]] && exit 0

echo
echo Invoke BATS tests.
bats test/test_*.bats

echo
echo Check every file for things like trailing whitespace.
ci/check-files -v1
